"""Birmingham Airport (BHX) destinations — May 2026."""

DESTINATIONS = {
    "BHX": {
        "name": "Birmingham",
        "routes": {
            "ABZ": "Aberdeen",
            "ACE": "Lanzarote",
            "ADB": "Izmir",
            "AGA": "Agadir",
            "AGP": "Malaga",
            "ALC": "Alicante",
            "AMS": "Amsterdam",
            "ARN": "Stockholm",
            "ATH": "Athens",
            "AYT": "Antalya",
            "BCN": "Barcelona",
            "BER": "Berlin",
            "BFS": "Belfast Intl",
            "BGY": "Milan Bergamo",
            "BHD": "Belfast City",
            "BJV": "Bodrum",
            "BOD": "Bordeaux",
            "BOJ": "Bourgas",
            "BRU": "Brussels",
            "BUD": "Budapest",
            "BVA": "Paris Beauvais",
            "BZG": "Bydgoszcz",
            "CDG": "Paris CDG",
            "CFU": "Corfu",
            "CGN": "Cologne Bonn",
            "CHQ": "Chania",
            "CIA": "Rome Ciampino",
            "CMF": "Chambery",
            "CPH": "Copenhagen",
            "CRA": "Craiova",
            "CRL": "Brussels Charleroi",
            "CTA": "Catania",
            "DBV": "Dubrovnik",
            "DLM": "Dalaman",
            "DUB": "Dublin",
            "DUS": "Dusseldorf",
            "EDI": "Edinburgh",
            "EFL": "Kefalonia",
            "EMA": "East Midlands",
            "FAO": "Faro",
            "FCO": "Rome Fiumicino",
            "FNC": "Funchal",
            "FRA": "Frankfurt",
            "FUE": "Fuerteventura",
            "GCI": "Guernsey",
            "GDN": "Gdansk",
            "GIB": "Gibraltar",
            "GLA": "Glasgow",
            "GNB": "Grenoble",
            "GRO": "Girona",
            "GVA": "Geneva",
            "HEL": "Helsinki",
            "HER": "Heraklion",
            "IBZ": "Ibiza",
            "INN": "Innsbruck",
            "INV": "Inverness",
            "IOM": "Isle of Man",
            "IST": "Istanbul",
            "JER": "Jersey",
            "JSI": "Skiathos",
            "JTR": "Santorini",
            "KAO": "Kuusamo",
            "KEF": "Reykjavik",
            "KGS": "Kos",
            "KLX": "Kalamata",
            "KRK": "Krakow",
            "KVA": "Kavala",
            "LCA": "Larnaca",
            "LCJ": "Lodz",
            "LDY": "Derry",
            "LEI": "Almeria",
            "LIS": "Lisbon",
            "LPA": "Gran Canaria",
            "LYS": "Lyon",
            "MAD": "Madrid",
            "MAH": "Menorca",
            "MJT": "Lesvos",
            "MLA": "Malta",
            "MUC": "Munich",
            "MXP": "Milan Malpensa",
            "NAP": "Naples",
            "NBE": "Enfidha",
            "NCE": "Nice",
            "NOC": "Knock",
            "NTE": "Nantes",
            "OLB": "Olbia",
            "OPO": "Porto",
            "ORK": "Cork",
            "ORY": "Paris Orly",
            "OTP": "Bucharest",
            "PDV": "Plovdiv",
            "PFO": "Paphos",
            "PGF": "Perpignan",
            "PMI": "Palma",
            "PMO": "Palermo",
            "POZ": "Poznan",
            "PRG": "Prague",
            "PSA": "Pisa",
            "PUY": "Pula",
            "PVK": "Preveza",
            "RAK": "Marrakesh",
            "REU": "Reus",
            "RHO": "Rhodes",
            "RIX": "Riga",
            "RMU": "Murcia",
            "RVN": "Rovaniemi",
            "SAW": "Istanbul Sabiha Gokcen",
            "SCV": "Suceava",
            "SDR": "Santander",
            "SKG": "Thessaloniki",
            "SMI": "Samos",
            "SNN": "Shannon",
            "SOF": "Sofia",
            "SPU": "Split",
            "SVQ": "Seville",
            "SZG": "Salzburg",
            "TFS": "Tenerife South",
            "TIA": "Tirana",
            "TIV": "Tivat",
            "TLL": "Tallinn",
            "TLS": "Toulouse",
            "TRN": "Turin",
            "TSF": "Venice Treviso",
            "VCE": "Venice Marco Polo",
            "VIE": "Vienna",
            "VLC": "Valencia",
            "VRN": "Verona",
            "WAW": "Warsaw Chopin",
            "WMI": "Warsaw Modlin",
            "XRY": "Jerez",
            "ZAD": "Zadar",
            "ZRH": "Zurich",
            "ZTH": "Zante",
        },
    },
}


def get_destinations(airport: str) -> dict:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("routes", {})


def get_airport_name(airport: str) -> str:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("name", airport)
